typography_spectrum: 0.6903263069689274
color:
  brandColors:
    - '#000000'
    - '#575757'
    - '#727272'
    - '#fbfbfb'
    - '#d2d2d2'
  brandStrength: 0
  lightness: 0
  saturation: 1
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: COMPLETE
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: CompleteDrums
purpose: []
