name: COMPLETE
favicon: null
layout_spectrum: 0.52021
typography_spectrum: 0.6903263069689274
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#575757'
    - '#727272'
    - '#fbfbfb'
    - '#d2d2d2'
  brandStrength: 0
  lightness: 0
  saturation: 1
  rhythmicContrast: 1
purpose: []
